# Generated by Django 3.1.6 on 2021-02-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='nedocs_score',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Busy', 'Busy'), ('Overcrowded', 'Overcrowded'), ('Severe', 'Severe')], default='Normal', max_length=100, null=True),
        ),
    ]
