# Generated by Django 3.1.6 on 2021-02-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='diversions',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='nedocs_score',
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(null=True)),
                ('nedocs_score', models.CharField(choices=[('Severe', 'Severe'), ('Normal', 'Normal'), ('Busy', 'Busy')], default='Normal', max_length=100, null=True)),
                ('diversions', models.ManyToManyField(blank=True, to='hospitals.Diversion')),
            ],
        ),
    ]
