# Generated by Django 3.1.6 on 2021-02-22 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_auto_20210222_0227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='H_Status',
        ),
    ]
