# Generated by Django 3.1.6 on 2021-02-22 02:45

from django.db import migrations, models
import hospitals.models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_auto_20210222_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=hospitals.models.Hospital)),
                ('last_updated', models.DateTimeField(null=True)),
                ('nedocs_score', models.CharField(choices=[('Severe', 'Severe'), ('Normal', 'Normal'), ('Busy', 'Busy')], default='Normal', max_length=100, null=True)),
                ('diversions', models.ManyToManyField(blank=True, to='hospitals.Diversion')),
            ],
        ),
        migrations.DeleteModel(
            name='H_Status',
        ),
    ]
