# Generated by Django 3.1.6 on 2021-02-22 03:07

from django.db import migrations, models
import hospitals.models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_auto_20210222_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='id',
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name=hospitals.models.Hospital),
        ),
    ]
