# Generated by Django 3.1.6 on 2021-02-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_hospital_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='diversions',
            field=models.ManyToManyField(blank=True, to='hospitals.Diversion'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='nedocs_score',
            field=models.CharField(choices=[('Severe', 'Severe'), ('Normal', 'Normal'), ('Busy', 'Busy')], default='Normal', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
