# Generated by Django 3.1.6 on 2021-02-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0008_auto_20210223_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='rch',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
