# Generated by Django 3.1.6 on 2021-02-23 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0009_auto_20210223_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='The phone number must only contain numbers in the format 01234567890', regex='^[0-9]*$')], verbose_name='phone number'),
        ),
    ]
