# Generated by Django 3.1.6 on 2021-02-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_auto_20210222_2233'),
        ('hospitals', '0010_auto_20210223_1859'),
    ]

    operations = [
    ]
